### ISSUE TITLE
Wrong expectations from the request method

### ISSUE THREAD

**Issue by gernest** [gernest/bearcub#1]
@pytlesk4  this sample https://github.com/gernest/bearcub/blob/master/variable_test.go#L112-L150 seems to have wrong expectation.

 go can't  parse request with  method of format `{method}` . This test case will always make the test fail when the method variable is missing because ` httputil.DumpRequestOut` will always return an error.

**Comment by pytlesk4** [comment]
Delete it please, I forgot to remove before sending this to you. Going to update this now. Sorry about that.

**Comment by pytlesk4** [comment]
Ultimately though, you can change the test so that it works. Essentially, if a variable is not found we should move on, leaving the string unchanged. So just add a path to the url, and set the path to a variable that doesn't exist.

**Comment by gernest** [comment]
@pytlesk4 the issue here is, when you leave the string unchanged it is supposed to pass the tests (conforming to expectation) which in our case it doesn't.

If I skip dumping the request, it destroys the whole point of the test case because we will never have output to compare with the expected string.

**Comment by pytlesk4** [comment]
Totally get that, I think deleting the test is completely fine. I was suggesting updating the input and expected result for the test case. So changing {method} to GET in both expected and input and then setting the path to something like /{undefined} in expected and input.

**Comment by gernest** [comment]
That is okay too, I can add `"method":"GET"` on the variables object and it will work well. However the point of the test case  I assume was to check handling of variables that don't exists , which happens to be covered by another test case.

A request with method `{method}` is invalid, unless I missed somethings. For the sake of making this work it will require working around `httputil.DumpRequestOut` .

It is your call though, just let me know If you which way you think I should go.
