### ISSUE TITLE
Do you want to stop the timer?

### ISSUE THREAD

**Issue by pytlesk4** [gernest/bearcub#2]
https://github.com/gernest/bearcub/blob/b33fd7cf7f98fd566305ddeb360fdc3b702cc3df/variable_bench_test.go#L29

**Comment by gernest** [comment]
@pytlesk4  my bad, I missed that, I wanted to stop so I can initialize the values without including them in the benchmarks.

**Comment by pytlesk4** [comment]
Totally, figured it was just a typo. Wish it was a little bit easier to check reset things in benchmarks, maybe go2 will have that.

**Comment by gernest** [comment]
Haven't seen much discussion on benchmarks for go2, everyone is on the generics debate, some are into war with `context`
